POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "Niko",
  "password": "Paco123",
  "email": "niko@gmail.com"
}

###

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email": "paco@gmail.com",
  "password": "Paco123"
}

###
POST http://localhost:3000/api/users/5f2fd45d298e1f00a4944710/posts
Content-Type: application/json

{
  "text": "Ja sam Koraljka i štela bi prodata svoju peglu"
}

###
GET http://localhost:3000/api/users/5f2fd45d298e1f00a4944710/posts/5f31b000e9b6fe284ce5b6a8

###
DELETE http://localhost:3000/api/users/5f2fd45d298e1f00a4944710/posts/5f31b000e9b6fe284ce5b6a8